In [9]:
import numpy as np

# topic: the linearity of trace

# determine the relationship between tr(A)+tr(B) and tr(A+B)
A = np.random.randn(5,4)
B = np.random.randn(5,4)

tr_A = np.trace(A)
tr_B = np.trace(B)
print(A)
print(tr_A)
print(' ')
print(B)
print(tr_B)
print(' ')
print(tr_A+tr_B)
tr_AB = np.trace(A+B)
print(tr_AB)

# determine the relationship between tr(l*A) and l*tr(A)
l = np.random.randint(0,9)
l_A = l*np.array(A)

print(' ')
print(np.trace(l_A))
print(l*np.trace(A))

[[-6.13109520e-01 -1.47569132e+00 -1.84418743e+00  9.36290826e-01]
 [-3.69959717e-01  1.59531608e+00  5.69375993e-01  1.01727069e+00]
 [ 1.17121143e+00 -7.20426202e-01  6.99743934e-01 -1.08065115e+00]
 [ 7.88011997e-01  6.88591697e-01 -2.47882207e+00  4.76401813e-01]
 [-1.30200885e+00 -1.24043270e-04 -1.51167189e+00 -5.27410942e-01]]
2.1583523035593473
 
[[-3.41623779e-01 -1.56676224e+00  1.52956947e-01  3.11679408e+00]
 [ 4.69991482e-03  2.18358731e-01 -6.04983932e-01 -1.58981601e+00]
 [-8.14140635e-01  3.82446648e-01  9.87635317e-01  9.09493928e-01]
 [ 5.06670916e-02 -8.35215203e-01 -2.42691372e-03 -1.28011782e+00]
 [-4.72290149e-01  9.63998313e-01  2.17398835e+00  2.26070848e-01]]
-0.4157475537501767
 
1.7426047498091706
1.742604749809171
 
4.3167046071186945
4.3167046071186945


0.23529411764705882