In [3]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [6]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L)

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.51264879 -0.86808101]
 [-0.77696996 -0.39754965]
 [-1.45063227  1.475282  ]
 [-1.24776454  1.27913994]
 [ 0.44101972 -0.40591658]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
[[-0.3056765   0.          0.          0.          0.        ]
 [ 0.32275868 -1.38950139  0.          0.          0.        ]
 [-0.02736304 -0.10563313 -0.60999402  0.          0.        ]
 [-0.2830995   1.04396863  0.17697525 -0.83963985  0.        ]
 [ 0.36266359 -1.66502725 -1.51790308 -0.7085237  -0.5680276 ]]
[[ 0.62074473  0.48732982 -0.45858028 -0.3959514   0.55638089  1.59620636]
 [ 0.42301856  0.53266318 -0.63651075 -0.39918045 -2.77270094 -0.73917004]
 [ 1.14283993  0.30985509  0.41266518  0.00351654 -0.39159748  1.93755264]]



---
# VIDEO: Matrix addition and subtraction
---


In [7]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,4)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(Ds)

[[ 0.18136271 -1.22667198 -0.2019013  -0.59662308  0.11404213]
 [ 0.2116193  -0.61835874  0.03951515  1.36400015 -1.97018702]
 [-1.5586345  -0.16109712 -1.48385736  0.54899659 -0.60887856]
 [ 1.20139127 -0.0980958  -0.4621352  -0.34459005  1.01802955]
 [-0.51401207 -0.78158042  1.01778231 -0.14314642 -0.24150726]]



---
# VIDEO: Matrix-scalar multiplication
---


In [43]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]



---
# VIDEO: Diagonal and trace
---


In [10]:

M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print(tr2)

[  4.  10.   4.   3.]
[[  4.   0.   0.   0.]
 [  0.  10.   0.   0.]
 [  0.   0.   4.   0.]
 [  0.   0.   0.   3.]]
21.0
21.0
