In [1]:
# create 2 4x6 matrices of random numbers

import numpy as np
import random as rnd

def matrix_gen(x,y,num=rnd):
    
    matrix=[]
    for i in range(x):
        column=[]
        for r in range(y):
            column.append(rnd.randint(0,100))
        matrix.append(column)
    
    return np.array(matrix)

A=matrix_gen(4,6)
B=matrix_gen(4,6)
print(A)
print(B)

[[51 64  8 86 76 79]
 [22 87  6 19 25 46]
 [31 66 76 64 91 94]
 [42 49 10 94  0 15]]
[[81 95 21 50 84 71]
 [26  0 64 30  0 88]
 [ 0 67 56 77 33 88]
 [51 13 23 61 92 63]]


In [6]:
# Us a for loop to compute dot product between corresponding columnss
def dot_prod_matrix(a,b):
    a_shape=a.shape
    b_shape=b.shape
    
    if a_shape==b.shape:
        dp=0
        for i in range(a_shape[0]):
            dp_matrix=[]
            for r in range(a_shape[1]):
                dp = dp + a[i][r]*b[i][r]
                dp_matrix.append(dp)
        return np.sum(dp_matrix)
    else:
        return 'Matrix A does not match B'

dot_prod_matrix(A,B)

377866