In [28]:
# create 2 4x6 matrices of random numbers

import numpy as np
import random as rnd

def matrix_gen(x,y,num=rnd):
    
    matrix=[]
    for i in range(x):
        column=[]
        for r in range(y):
            column.append(rnd.randint(-10,10))
        matrix.append(column)
    
    return np.array(matrix)

A=matrix_gen(4,6)
B=matrix_gen(4,6)
print(A)
print(B)

[[  4  -6   0   4   0  -5]
 [ -9   7   1  -2   8   1]
 [ -7   6   8  -9   9 -10]
 [  2  -5   6   0   1  -6]]
[[-9 -4 -7  3 -9  7]
 [-4  8 -2 -6 10 -1]
 [10 -3  2  1  8  2]
 [-7  6 -7  2  7  1]]


In [30]:
# Us a for loop to compute dot product between corresponding columnss
def dot_prod_matrix(a,b):
    a_shape=a.shape
    b_shape=b.shape
    
    if a_shape==b.shape:
        dp_matrix=[]
        for i in range(a_shape[1]):
            dp_matrix.append(np.dot(a[:,i],b[:,i]))
                
        return np.transpose(dp_matrix)
    else:
        return 'Matrix A does not match B'

dot_prod_matrix(A,B)

array([-84,  32, -28,  15, 159, -62])