In [1]:
# implement matrix multiplication via layers
import numpy as np
import pandas as pd

m = 4
n = 6
A = np.random.randint(10,size=(m,n))
B = np.random.randint(10,size=(n,m))
print(A)
print('')
print(B)

[[0 3 0 9 8 9]
 [8 2 8 4 2 3]
 [4 2 2 3 7 7]
 [3 1 6 6 8 2]]

[[8 0 4 6]
 [2 1 4 3]
 [4 8 9 3]
 [5 6 8 0]
 [7 4 3 2]
 [3 0 1 3]]


In [2]:
def mat_mult_lay(a,b):
    out_prod =  []
    m = len(a)
    n = len(b)
    def outerprod(dimmension):
        out_prod = []
        for j in range(m):
            col = a[j][dimmension]   
            in_arr = [] 
            for i in range(m):
                row = b[dimmension][i]
                in_arr.append(col*row)
            out_prod.append(in_arr)
        return out_prod

    mat_mult = np.zeros(m, dtype=int)
    for x in range(n):
        mat_mult = mat_mult + outerprod(x)
        
    return mat_mult
finn = mat_mult_lay(A,B)
print(finn)

[[134  89 117  52]
 [143  98 153  91]
 [129  64  94  71]
 [142 117 144  61]]


In [3]:
print('Finn Layer Matrix Multiplication')
print(finn)

comp = np.matmul(A,B)
print('Mat Mult')
print(comp)

Finn Layer Matrix Multiplication
[[134  89 117  52]
 [143  98 153  91]
 [129  64  94  71]
 [142 117 144  61]]
Mat Mult
[[134  89 117  52]
 [143  98 153  91]
 [129  64  94  71]
 [142 117 144  61]]


In [4]:
print('Performance Check')
print(finn-comp)

Performance Check
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
