In [25]:
# create two 4 x 4 matricies: full and diagnal matrix.
import numpy as np
# Full
n = int(np.random.randn()*100)
print(n)
A = np.full((4, 4), n)
print('Full')
print(A)

# Diagonal
B = np.zeros((4, 4), int)
np.fill_diagonal(B, n)
print('Diagonal')
print(B)

10
Full
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
Diagonal
[[10  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 10]]


In [31]:
# multiply each matrix by itself standard and hadamard multiplications. 

# hadamard full
print('')
had_A = np.multiply( A,A )
print('hadamard full')
print(had_A)

# hadamard diagonal
print('')
had_B = np.multiply( B,B )
print('hadamard diagonal')
print(had_B)

# standard full
print('')
stan_A = np.matmul(A,A)
print('standard full')
print(stan_A)

# standard diagonal
print('')
stan_B = np.matmul(B,B)
print('standard diagonal')
print(stan_B)

print('')
print('had_A == had_B')
print(np.array_equal(had_A,had_B))

print('')
print('stan_A == stan_B')
print(np.array_equal(stan_A,stan_B))


hadamard full
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]

hadamard diagonal
[[100   0   0   0]
 [  0 100   0   0]
 [  0   0 100   0]
 [  0   0   0 100]]

standard full
[[400 400 400 400]
 [400 400 400 400]
 [400 400 400 400]
 [400 400 400 400]]

standard diagonal
[[100   0   0   0]
 [  0 100   0   0]
 [  0   0 100   0]
 [  0   0   0 100]]

had_A == had_B
False

stan_A == stan_B
False
