In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [17]:
# create two symetric matricies
n = 4
m= 6
A_rand = np.random.randint(10,size=(n,n))
A = (A_rand + np.transpose(A_rand))/2
B_rand = np.random.randint(10,size=(n,n))
B = (B_rand + B_rand.T)/2
print('Matrix A')
print(A)
print('')
print('Matrix B')
print(B)

# Compute the sum, multiplication, and Hadamard multiplication of the two matricies
print('')
print('Sum')
sum_m = np.matrix.transpose(A)@A+np.matrix.transpose(B)@B
print(sum_m)
print('Multiplication')
multi_m = np.matrix.transpose(A)@A*np.matrix.transpose(B)@B
print(multi_m)
print('Hadamard Multiplication')
multi_h = np.multiply(np.matrix.transpose(A)@A,np.matrix.transpose(B)@B)
print(multi_h)

# Determine if the result is still symetric
print('')
print('Sum')
print(np.equal(sum_m,np.transpose(sum_m)))
print('Multiplication')
print(np.equal(multi_m,np.transpose(multi_m)))
print('Hadamard Multiplication')
print(np.equal(multi_h,np.transpose(multi_h)))

Matrix A
[[9.  6.  3.  6. ]
 [6.  0.  5.  4.5]
 [3.  5.  5.  4. ]
 [6.  4.5 4.  2. ]]

Matrix B
[[7.  2.  9.  7. ]
 [2.  6.  1.  4.5]
 [9.  1.  5.  7.5]
 [7.  4.5 7.5 2. ]]

Sum
[[345.   162.5  258.5  244.5 ]
 [162.5  142.5  123.75 122.5 ]
 [258.5  123.75 238.25 188.5 ]
 [244.5  122.5  188.5  205.75]]
Multiplication
[[21243.     7591.5   20230.5   16752.   ]
 [ 4915.5    4686.25   4714.25   4580.25 ]
 [13141.25   4780.875 13565.125 10162.5  ]
 [11421.25   4425.    10620.    10619.375]]
Hadamard Multiplication
[[29646.      6384.     15600.     14647.5   ]
 [ 6384.      4976.5625  3827.75    3737.5   ]
 [15600.      3827.75   12243.75    8220.    ]
 [14647.5     3737.5     8220.      9874.375 ]]

Sum
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
Multiplication
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
Hadamard Multiplication
[[ True  True  True  True]
 [ True